[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "orca_arm"
version = "0.1.0"
description = "Orca robot descriptions with bundled URDF/MJCF assets, including single arm and bimanual setups.
readme = "README.md"
requires-python = ">=3.10"
authors = [{ name = "Francesco Capuano" , email = "capuano@robots.ox.ac.uk"}]

[tool.setuptools]
packages = ["orca_arm"]
include-package-data = true

[project.optional-dependencies]
viz = [
    "meshcat",
    "yourdfpy",
    "mujoco"
]
build = [
    "mujoco",
    "numpy",
    "trimesh",
    "xacro",
]

[tool.setuptools.package-data]
orca_arm = [
    "THIRD_PARTY_NOTICES.md",
    "orcabot.urdf",
    "orcabot.xml",
    "orcapanda.urdf",
    "orcapanda.xml",
    "bimanual_orcapanda.urdf",
    "bimanual_orcapanda.xml",
    "assets/*.stl",
    "assets/*.dae",
    "assets/*.obj",
    "assets/*.STL",
    "assets/*.DAE",
    "assets/franka_emika_panda/*",
]
